# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-18 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200318_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenre',
            name='genre',
            field=models.CharField(max_length=50, verbose_name='Genre'),
        ),
    ]
