# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-18 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200318_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenre',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Action'), (2, 'Adventure'), (3, 'Comedy'), (4, 'Crime'), (5, 'Drama'), (6, 'Historical')], verbose_name='Genre'),
        ),
    ]
