# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-24 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200318_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showdetail',
            name='end_time',
        ),
    ]
