# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-24 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_remove_showdetail_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showdetail',
            name='date',
        ),
        migrations.RemoveField(
            model_name='showdetail',
            name='start_time',
        ),
        migrations.AddField(
            model_name='showdetail',
            name='showdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 12, 37, 34, 202346)),
        ),
    ]
