# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-26 06:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200324_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showdetail',
            name='showdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 6, 25, 33, 868291)),
        ),
    ]
