# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-26 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
